CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(25) NOT NULL UNIQUE,
    phone_number VARCHAR(15) UNIQUE,
    password VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    country_id BIGINT NOT NULL,
    CONSTRAINT fk_users_country
        FOREIGN KEY (country_id) REFERENCES countries(id)
);
