spring.application.name=nutrition_service

spring.datasource.url=jdbc:postgresql://localhost:5433/nutrition
spring.datasource.username=user
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

server.port=8082

logging.level.com.app.nutrition_service=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/