services:
  auth_bd:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AUTH_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nutrition_bd:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NUTRITION_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${NUTRITION_DB_PORT}:5432"
    volumes:
      - nutrition_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${NUTRITION_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_postgres_data:
  nutrition_postgres_data: