CREATE TABLE categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    item_type VARCHAR(10) NOT NULL CHECK (item_type IN ('food','drink'))
);

INSERT INTO categories (name, item_type) VALUES
('FRUITS','food'),
('VEGETABLES','food'),
('HERBS','food'),
('GRAINS','food'),
('PASTA','food'),
('BAKERY','food'),
('LEGUMES','food'),
('NUTS','food'),
('SEEDS','food'),
('MEAT','food'),
('POULTRY','food'),
('FISH','food'),
('SEAFOOD','food'),
('EGGS','food'),
('DAIRY','food'),
('CHEESE','food'),
('OILS_AND_FATS','food'),
('SWEETS','food'),
('SNACKS','food'),
('SAUCES','food'),
('SOUPS','food'),
('READY_MEALS','food'),
('FAST_FOOD','food'),
('BREAKFAST','food'),
('WATER','drink'),
('COFFEE','drink'),
('TEA','drink'),
('JUICES','drink'),
('SMOOTHIES','drink'),
('SOFT_DRINKS','drink'),
('ENERGY_DRINKS','drink'),
('SPORTS_DRINKS','drink'),
('MILK_DRINKS','drink'),
('PLANT_DRINKS','drink'),
('PROTEIN_DRINKS','drink'),
('SHAKES','drink'),
('OTHER_DRINKS','drink');